-- ============================================================================
-- WHERE IN THE WORLD IS SNOWFLAKE BOSEMAN MONTANA?
-- Seed Data for Reference Tables
-- ============================================================================

-- ============================================================================
-- LOCATIONS (100 cities across all continents)
-- Descriptions are NULL - will be generated by Cortex AI
-- ============================================================================

INSERT INTO locations (location_id, city, country, continent, latitude, longitude, description) VALUES
-- Europe
('loc_paris', 'Paris', 'France', 'Europe', 48.8566, 2.3522, NULL),
('loc_london', 'London', 'United Kingdom', 'Europe', 51.5074, -0.1278, NULL),
('loc_rome', 'Rome', 'Italy', 'Europe', 41.9028, 12.4964, NULL),
('loc_amsterdam', 'Amsterdam', 'Netherlands', 'Europe', 52.3676, 4.9041, NULL),
('loc_barcelona', 'Barcelona', 'Spain', 'Europe', 41.3851, 2.1734, NULL),

-- Asia
('loc_tokyo', 'Tokyo', 'Japan', 'Asia', 35.6762, 139.6503, NULL),
('loc_bangkok', 'Bangkok', 'Thailand', 'Asia', 13.7563, 100.5018, NULL),
('loc_mumbai', 'Mumbai', 'India', 'Asia', 19.0760, 72.8777, NULL),
('loc_singapore', 'Singapore', 'Singapore', 'Asia', 1.3521, 103.8198, NULL),
('loc_beijing', 'Beijing', 'China', 'Asia', 39.9042, 116.4074, NULL),

-- North America
('loc_newyork', 'New York City', 'United States', 'North America', 40.7128, -74.0060, NULL),
('loc_losangeles', 'Los Angeles', 'United States', 'North America', 34.0522, -118.2437, NULL),
('loc_mexico', 'Mexico City', 'Mexico', 'North America', 19.4326, -99.1332, NULL),
('loc_toronto', 'Toronto', 'Canada', 'North America', 43.6532, -79.3832, NULL),
('loc_sanfrancisco', 'San Francisco', 'United States', 'North America', 37.7749, -122.4194, NULL),

-- South America
('loc_rio', 'Rio de Janeiro', 'Brazil', 'South America', -22.9068, -43.1729, NULL),
('loc_buenosaires', 'Buenos Aires', 'Argentina', 'South America', -34.6037, -58.3816, NULL),
('loc_lima', 'Lima', 'Peru', 'South America', -12.0464, -77.0428, NULL),

-- Africa
('loc_cairo', 'Cairo', 'Egypt', 'Africa', 30.0444, 31.2357, NULL),
('loc_capetown', 'Cape Town', 'South Africa', 'Africa', -33.9249, 18.4241, NULL),
('loc_marrakech', 'Marrakech', 'Morocco', 'Africa', 31.6295, -7.9811, NULL),

-- Oceania
('loc_sydney', 'Sydney', 'Australia', 'Oceania', -33.8688, 151.2093, NULL),
('loc_auckland', 'Auckland', 'New Zealand', 'Oceania', -36.8509, 174.7645, NULL),

-- Antarctica (bonus challenging location)
('loc_mcmurdo', 'McMurdo Station', 'Antarctica', 'Antarctica', -77.8419, 166.6863, NULL),

-- Bozeman Montana - Home base!
('loc_bozeman', 'Bozeman', 'United States', 'North America', 45.6770, -111.0429, NULL),

-- Additional Europe (20 more cities)
('loc_berlin', 'Berlin', 'Germany', 'Europe', 52.5200, 13.4050, NULL),
('loc_vienna', 'Vienna', 'Austria', 'Europe', 48.2082, 16.3738, NULL),
('loc_prague', 'Prague', 'Czech Republic', 'Europe', 50.0755, 14.4378, NULL),
('loc_budapest', 'Budapest', 'Hungary', 'Europe', 47.4979, 19.0402, NULL),
('loc_athens', 'Athens', 'Greece', 'Europe', 37.9838, 23.7275, NULL),
('loc_lisbon', 'Lisbon', 'Portugal', 'Europe', 38.7223, -9.1393, NULL),
('loc_dublin', 'Dublin', 'Ireland', 'Europe', 53.3498, -6.2603, NULL),
('loc_edinburgh', 'Edinburgh', 'Scotland', 'Europe', 55.9533, -3.1883, NULL),
('loc_stockholm', 'Stockholm', 'Sweden', 'Europe', 59.3293, 18.0686, NULL),
('loc_copenhagen', 'Copenhagen', 'Denmark', 'Europe', 55.6761, 12.5683, NULL),
('loc_oslo', 'Oslo', 'Norway', 'Europe', 59.9139, 10.7522, NULL),
('loc_helsinki', 'Helsinki', 'Finland', 'Europe', 60.1699, 24.9384, NULL),
('loc_warsaw', 'Warsaw', 'Poland', 'Europe', 52.2297, 21.0122, NULL),
('loc_brussels', 'Brussels', 'Belgium', 'Europe', 50.8503, 4.3517, NULL),
('loc_zurich', 'Zurich', 'Switzerland', 'Europe', 47.3769, 8.5417, NULL),
('loc_munich', 'Munich', 'Germany', 'Europe', 48.1351, 11.5820, NULL),
('loc_milan', 'Milan', 'Italy', 'Europe', 45.4642, 9.1900, NULL),
('loc_venice', 'Venice', 'Italy', 'Europe', 45.4408, 12.3155, NULL),
('loc_florence', 'Florence', 'Italy', 'Europe', 43.7696, 11.2558, NULL),
('loc_istanbul', 'Istanbul', 'Turkey', 'Europe', 41.0082, 28.9784, NULL),

-- Additional Asia (20 more cities)
('loc_seoul', 'Seoul', 'South Korea', 'Asia', 37.5665, 126.9780, NULL),
('loc_hongkong', 'Hong Kong', 'China', 'Asia', 22.3193, 114.1694, NULL),
('loc_shanghai', 'Shanghai', 'China', 'Asia', 31.2304, 121.4737, NULL),
('loc_taipei', 'Taipei', 'Taiwan', 'Asia', 25.0330, 121.5654, NULL),
('loc_hanoi', 'Hanoi', 'Vietnam', 'Asia', 21.0278, 105.8342, NULL),
('loc_hochiminhcity', 'Ho Chi Minh City', 'Vietnam', 'Asia', 10.8231, 106.6297, NULL),
('loc_kualalumpur', 'Kuala Lumpur', 'Malaysia', 'Asia', 3.1390, 101.6869, NULL),
('loc_jakarta', 'Jakarta', 'Indonesia', 'Asia', -6.2088, 106.8456, NULL),
('loc_manila', 'Manila', 'Philippines', 'Asia', 14.5995, 120.9842, NULL),
('loc_delhi', 'Delhi', 'India', 'Asia', 28.7041, 77.1025, NULL),
('loc_kathmandu', 'Kathmandu', 'Nepal', 'Asia', 27.7172, 85.3240, NULL),
('loc_colombo', 'Colombo', 'Sri Lanka', 'Asia', 6.9271, 79.8612, NULL),
('loc_dhaka', 'Dhaka', 'Bangladesh', 'Asia', 23.8103, 90.4125, NULL),
('loc_osaka', 'Osaka', 'Japan', 'Asia', 34.6937, 135.5023, NULL),
('loc_kyoto', 'Kyoto', 'Japan', 'Asia', 35.0116, 135.7681, NULL),
('loc_dubai', 'Dubai', 'United Arab Emirates', 'Asia', 25.2048, 55.2708, NULL),
('loc_doha', 'Doha', 'Qatar', 'Asia', 25.2854, 51.5310, NULL),
('loc_telaviv', 'Tel Aviv', 'Israel', 'Asia', 32.0853, 34.7818, NULL),
('loc_jerusalem', 'Jerusalem', 'Israel', 'Asia', 31.7683, 35.2137, NULL),
('loc_baku', 'Baku', 'Azerbaijan', 'Asia', 40.4093, 49.8671, NULL),

-- Additional North America (15 more cities)
('loc_chicago', 'Chicago', 'United States', 'North America', 41.8781, -87.6298, NULL),
('loc_miami', 'Miami', 'United States', 'North America', 25.7617, -80.1918, NULL),
('loc_lasvegas', 'Las Vegas', 'United States', 'North America', 36.1699, -115.1398, NULL),
('loc_seattle', 'Seattle', 'United States', 'North America', 47.6062, -122.3321, NULL),
('loc_boston', 'Boston', 'United States', 'North America', 42.3601, -71.0589, NULL),
('loc_neworleans', 'New Orleans', 'United States', 'North America', 29.9511, -90.0715, NULL),
('loc_washingtondc', 'Washington D.C.', 'United States', 'North America', 38.9072, -77.0369, NULL),
('loc_denver', 'Denver', 'United States', 'North America', 39.7392, -104.9903, NULL),
('loc_vancouver', 'Vancouver', 'Canada', 'North America', 49.2827, -123.1207, NULL),
('loc_montreal', 'Montreal', 'Canada', 'North America', 45.5017, -73.5673, NULL),
('loc_havana', 'Havana', 'Cuba', 'North America', 23.1136, -82.3666, NULL),
('loc_cancun', 'Cancun', 'Mexico', 'North America', 21.1619, -86.8515, NULL),
('loc_guadalajara', 'Guadalajara', 'Mexico', 'North America', 20.6597, -103.3496, NULL),
('loc_panama', 'Panama City', 'Panama', 'North America', 8.9824, -79.5199, NULL),
('loc_sanjuan', 'San Juan', 'Puerto Rico', 'North America', 18.4655, -66.1057, NULL),

-- Additional South America (10 more cities)
('loc_bogota', 'Bogotá', 'Colombia', 'South America', 4.7110, -74.0721, NULL),
('loc_medellin', 'Medellín', 'Colombia', 'South America', 6.2476, -75.5658, NULL),
('loc_santiago', 'Santiago', 'Chile', 'South America', -33.4489, -70.6693, NULL),
('loc_quito', 'Quito', 'Ecuador', 'South America', -0.1807, -78.4678, NULL),
('loc_lapaz', 'La Paz', 'Bolivia', 'South America', -16.4897, -68.1193, NULL),
('loc_montevideo', 'Montevideo', 'Uruguay', 'South America', -34.9011, -56.1645, NULL),
('loc_cartagena', 'Cartagena', 'Colombia', 'South America', 10.3910, -75.4794, NULL),
('loc_cusco', 'Cusco', 'Peru', 'South America', -13.5320, -71.9675, NULL),
('loc_saopaulo', 'São Paulo', 'Brazil', 'South America', -23.5505, -46.6333, NULL),
('loc_salvador', 'Salvador', 'Brazil', 'South America', -12.9714, -38.5014, NULL),

-- Additional Africa (10 more cities)
('loc_nairobi', 'Nairobi', 'Kenya', 'Africa', -1.2921, 36.8219, NULL),
('loc_johannesburg', 'Johannesburg', 'South Africa', 'Africa', -26.2041, 28.0473, NULL),
('loc_lagos', 'Lagos', 'Nigeria', 'Africa', 6.5244, 3.3792, NULL),
('loc_accra', 'Accra', 'Ghana', 'Africa', 5.6037, -0.1870, NULL),
('loc_addisababa', 'Addis Ababa', 'Ethiopia', 'Africa', 9.0320, 38.7469, NULL),
('loc_dakar', 'Dakar', 'Senegal', 'Africa', 14.7167, -17.4677, NULL),
('loc_casablanca', 'Casablanca', 'Morocco', 'Africa', 33.5731, -7.5898, NULL),
('loc_tunis', 'Tunis', 'Tunisia', 'Africa', 36.8065, 10.1815, NULL),
('loc_luxor', 'Luxor', 'Egypt', 'Africa', 25.6872, 32.6396, NULL),
('loc_zanzibar', 'Zanzibar City', 'Tanzania', 'Africa', -6.1659, 39.2026, NULL),

-- Additional Oceania (5 more cities)
('loc_melbourne', 'Melbourne', 'Australia', 'Oceania', -37.8136, 144.9631, NULL),
('loc_brisbane', 'Brisbane', 'Australia', 'Oceania', -27.4698, 153.0251, NULL),
('loc_perth', 'Perth', 'Australia', 'Oceania', -31.9505, 115.8605, NULL),
('loc_wellington', 'Wellington', 'New Zealand', 'Oceania', -41.2866, 174.7756, NULL),
('loc_suva', 'Suva', 'Fiji', 'Oceania', -18.1416, 178.4419, NULL);

-- ============================================================================
-- SUSPECTS (12 colorful villains)
-- ============================================================================

INSERT INTO suspects (suspect_id, name, hair_color, eye_color, hobby, vehicle, favorite_food, distinguishing_feature) VALUES
('sus_boseman', 'Snowflake Boseman Montana', 'Silver-white', 'Ice blue', 'Data hoarding', 'Snowmobile', 'Frozen treats', 'Always leaves a trail of snowflakes'),
('sus_carmen', 'Carmen Sandiego-Inspired', 'Black', 'Brown', 'Stealing landmarks', 'Red convertible', 'Paella', 'Wears a signature red trench coat'),
('sus_byte', 'Binary Byte', 'Green (dyed)', 'Hazel', 'Hacking', 'Electric scooter', 'Ramen', 'Types furiously on a vintage keyboard'),
('sus_query', 'Query McSelectson', 'Bald', 'Gray', 'Writing SQL', 'Database-themed van', 'Table salt on everything', 'Mutters SELECT statements constantly'),
('sus_null', 'Null Pointer', 'Invisible (shaved)', 'Unknown', 'Crashing systems', 'Teleportation', 'Nothing', 'Causes exceptions wherever they go'),
('sus_pip', 'Pip Install', 'Purple', 'Green', 'Package management', 'Python-wrapped motorcycle', 'Snake fruit', 'Leaves dependency conflicts behind'),
('sus_cache', 'Cache Money', 'Gold', 'Golden', 'Collecting valuables', 'Armored cache truck', 'Expensive caviar', 'Everything they touch turns to cache'),
('sus_merge', 'Merge Conflict', 'Half black, half white', 'One blue, one brown', 'Creating chaos', 'Split-colored car', 'Mixed dishes', 'Leaves conflicting clues everywhere'),
('sus_docker', 'Docker Whale', 'Blue', 'Deep sea blue', 'Container shipping', 'Cargo ship', 'Seafood', 'Always travels in containers'),
('sus_git', 'Git Blame', 'Red', 'Shifty brown', 'Pointing fingers', 'Branch-hopping vehicle', 'Blame game cookies', 'Never takes responsibility'),
('sus_cloud', 'Cloudy McFloatface', 'Wispy white', 'Sky blue', 'Weather manipulation', 'Hot air balloon', 'Cloud-shaped candy', 'Floats into cities unannounced'),
('sus_api', 'API Endpoint', 'Rainbow (changes daily)', 'REST-ful gray', 'Making connections', 'Any vehicle that requests', 'JSON-formatted food', 'Responds differently to everyone');

-- ============================================================================
-- Generate descriptions using Cortex AI (AI_COMPLETE)
-- Run this after the INSERT statements to populate AI-generated content
-- See: https://docs.snowflake.com/en/sql-reference/functions/ai_complete-single-string
-- ============================================================================

-- Generate enhanced location descriptions using AI_COMPLETE
UPDATE locations SET description = AI_COMPLETE(
    model => 'llama3.1-8b',
    prompt => CONCAT(
        'You are writing for a family-friendly geography game similar to Carmen Sandiego. ',
        'Write a 2-sentence travel guide description for ', city, ', ', country, '. ',
        'Focus on what makes it unique and exciting for tourists. ',
        'Keep it educational, fun, and appropriate for all ages. ',
        'Do not include any unsafe or controversial content.'
    ),
    model_parameters => {'guardrails': TRUE}
)
WHERE description IS NULL;

SELECT 'Seed data inserted. Cortex AI descriptions generated.' as status;
